VMName: UbuntuVM
VMMemory: 8192
VMDiskSize: 20480
ISOPath: C:\path\to\ubuntu.iso
VMUsername: myusername
VMPassword: stdin
VMHostname: teste123
VMLocale: pt_PT
VMCountry: PT
VMTimezone: WET
VMDiskPath: C:\path\to\vdi.vdi
VMSnapshot: Base
