VMName: UbuntuVM
VMMemory: 8192
VMDiskSize: 20480
ISOPath: C:\path\to\ubuntu.iso
FullUsername:
Username: myusername
PasswordFile: stdin
Hostname: vmname.myguest.virtualbox.org
Locale: pt_PT
Country: PT
Timezone: WET
DiskPath: C:\path\to\vdi.vdi
Snapshot: Base
ProductKey:
InstallAdditions: True
AdditionsISO: C:\path\to\Additions
TXS:
PackageSelectionAdjustment:
DryRun: False
StartVM: headless
AuxilaryBasePath:
WindowsImageIndex:
ScriptTemplate:
PostInstallTemplate:
PostInstallCommand:
ExtraInstallKernelParams:
WindowsLanguage: